const portfolio = [
    {
        name: '90theme-version-1',
        type: 'website',
        design: 'Pourghannad',
        development: 'Pourghannad',
        platform: 'WordPress',
        description: '',
        createdAt: '2013',
        link: '',
        image: '',
    },
    {
        name: 'WNovin',
        type: 'gif',
        design: 'Pourghannad',
        development: '',
        platform: 'gif-banner',
        description: '',
        createdAt: '2014',
        link: '',
        image: './wnovin.gif',
    },
    {
        name: 'MihanIT',
        type: 'gif',
        design: 'Pourghannad',
        development: '',
        platform: 'gif-banner',
        description: '',
        createdAt: '2014',
        link: '',
        image: './mihanit.gif',
    },
    {
        name: 'ArkaNet',
        type: 'gif',
        design: 'Pourghannad',
        development: '',
        platform: 'gif-banner',
        description: '',
        createdAt: '2014',
        link: '',
        image: './arkanet.gif',
    },
    {
        name: 'pourghannad.ir-v1',
        type: 'website',
        design: 'Pourghannad',
        development: 'Pourghannad',
        platform: 'html',
        description: '',
        createdAt: '2014',
        link: '',
        image: './pourghannad-ir-v1.png',
    },
    {
        name: 'skimoo',
        type: 'website',
        design: 'ivahid',
        development: 'Pourghannad',
        platform: 'WordPress',
        description: '',
        createdAt: '2015',
        link: '',
        image: '',
    },
    {
        name: '80200',
        type: 'website',
        design: 'Pourghannad',
        development: 'Pourghannad',
        platform: 'html',
        description: '',
        createdAt: '2015',
        link: '',
        image: '',
    },
    {
        name: 'loxit',
        type: 'website',
        design: 'Pourghannad',
        development: 'Pourghannad',
        platform: 'html',
        description: '',
        createdAt: '2015',
        link: '',
        image: '',
    },{
        name: '20script froum',
        type: 'website',
        design: 'ivahid',
        development: 'Pourghannad',
        platform: 'vbulletin',
        description: '',
        createdAt: '2015',
        link: '',
        image: '',
    },
]