export const portfolio = [
  {
    name: "Hamrahtel Incredibles Landing",
    type: "website",
    design: "Hamrahtel team",
    development: "Pourghannad",
    technology: ["react", "typescript", "tailwind"],
    description: "",
    createdAt: "2025",
    link: "https://hamrahtel.com/incredibles",
    images: ["./img/hamrahtel-incredibles-landing.png"],
  },
  {
    name: "Hamrahtel App Landing",
    type: "website",
    design: "Hamrahtel team",
    development: "Pourghannad",
    technology: ["react", "typescript", "tailwind"],
    description: "",
    createdAt: "2025",
    link: "https://hamrahtel.com/app",
    images: ["./img/hamrahtel-app-landing.png"],
  },
  {
    name: "gsm.ir backoffice",
    type: "website",
    design: "Hamrahtel team",
    technology: [
      "react",
      "typescript",
      "react-query",
      "material-ui",
      "react-hook-form",
      "workbox",
      "jotai",
      "i18n",
    ],
    description: "",
    createdAt: "2025",
    memberOfTeam: true,
    link: "https://gbo.gsm.ir/",
    images: ["./img/gbo.png"],
  },
  {
    name: "Hamrahtel warehouse",
    type: "website",
    design: "Hamrahtel team",
    technology: [
      "react",
      "typescript",
      "react-query",
      "material-ui",
      "react-hook-form",
      "workbox",
      "jotai",
      "i18n",
    ],
    description: "",
    createdAt: "2025",
    memberOfTeam: true,
    link: "https://warehouse.hamrahtel.com/",
    images: ["./img/hamrahtel-warehouse.png"],
  },
  {
    name: "Hamrahtel backoffice",
    type: "website",
    design: "Hamrahtel team",
    technology: [
      "react",
      "typescript",
      "react-query",
      "material-ui",
      "react-hook-form",
      "workbox",
      "graphql",
      "i18n",
    ],
    description: "",
    createdAt: "2025",
    memberOfTeam: true,
    link: "https://admin.hamrahtel.com/",
    images: ["./img/hamrahtel-admin.png"],
  },
  {
    name: "Hamrahtel pwa",
    type: "pwa",
    design: "Hamrahtel team",
    technology: [
      "react",
      "typescript",
      "react-query",
      "tailwind",
      "react-hook-form",
      "workbox",
      "shadcn",
      "jotai",
      "graphql",
    ],
    description: "",
    createdAt: "2025",
    memberOfTeam: true,
    link: "https://app.hamrahtel.com/",
    images: [
      "./img/hamrahtel-app.png",
      "./img/hamrahtel-app-2.png",
      "./img/hamrahtel-app-3.png",
    ],
  },
  {
    name: "youCube twa",
    type: "pwa",
    design: "youCube team",
    technology: [
      "react",
      "typescript",
      "react-query",
      "jotai",
      "scss-modules",
      "react-hook-form",
    ],
    description: "",
    createdAt: "2024",
    memberOfTeam: true,
    link: "https://app.youcube.ai",
    images: ["./img/youcube.png", "./img/youcube2.png"],
  },
  {
    name: "youCube landing",
    type: "website",
    design: "Bahar Arsooni",
    technology: ["react", "scss", "react-helmet", "spline"],
    description: "",
    createdAt: "2024",
    memberOfTeam: true,
    link: "https://youcube.ai/",
    images: ["./img/ucube-landing.png"],
  },
  {
    name: "panj.monster",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html", "css"],
    description: "",
    createdAt: "2021",
    link: "https://pourghannad.github.io/panj.monster/",
    images: ["./img/panj-monster.png"],
  },
  {
    name: "karaz care",
    type: "website",
    design: "karaz team",
    technology: ["nextjs", "material-ui", "jest", "styled-components"],
    description: "",
    createdAt: "2024",
    memberOfTeam: true,
    link: "",
    images: ["./img/karaz-care.png", "./img/karaz-care-2.png"],
  },
  {
    name: "karaz data panel",
    type: "website",
    design: "",
    technology: ["react", "material-ui", "material-react-table"],
    description: "",
    createdAt: "2024",
    link: "",
    images: [],
  },
  {
    name: "rapidpacecrm panel",
    type: "website",
    design: "RTA team",
    technology: ["react", "i18n", "micro-frontend", "redux-saga", "ant-design"],
    description: "",
    memberOfTeam: true,
    createdAt: "2023",
    link: "",
    images: ["./img/urm.png"],
  },
  {
    name: "rapidpacecrm",
    type: "website",
    design: "RTA team",
    technology: ["webflow"],
    description: "",
    memberOfTeam: true,
    createdAt: "2023",
    link: "https://rapidpacecrm.com",
    images: ["./img/rapidpace.png"],
  },
  {
    name: "Carriot backoffice",
    type: "website",
    design: "Carriot Team",
    technology: ["react", "typescript", "nextjs", "material ui", "gRPC"],
    description: "",
    memberOfTeam: true,
    createdAt: "2023",
    link: "https://panel.carriot.ir/login",
    images: ["./img/carriot.png"],
  },
  {
    name: "5Page",
    type: "open-source",
    design: "pourghannad",
    development: "pourghannad",
    technology: ["react", "scss-modules"],
    description: "",
    createdAt: "2022",
    link: "https://pourghannad.github.io/5page/",
    images: ["./img/5page.png"],
  },
  {
    name: "Sabaidea SSO V2",
    type: "website",
    design: "Sabaidea Team",
    technology: ["react", "typescript", "i18n"],
    description: "",
    memberOfTeam: true,
    createdAt: "2022",
    link: "https://www.filimo.com/signin",
    images: ["./img/sabaidea-sso.png"],
  },
  {
    name: "sc-weather",
    type: "open-source",
    design: "pourghannad",
    development: "pourghannad",
    technology: ["webpack", "scss", "VanillaJs"],
    description: "",
    createdAt: "2021",
    link: "https://azardnet.github.io/sc-weather/",
    images: ["./img/sc-weather.png"],
  },
  {
    name: "Aparat2",
    type: "website",
    design: "Sabaidea Team",
    technology: [
      "react",
      "typescript",
      "i18n",
      "redux-saga",
      "react-hook-form",
      "styled-components",
    ],
    description: "",
    memberOfTeam: true,
    createdAt: "2021",
    link: "https://aparat.com",
    images: ["./img/aparat.png"],
  },
  {
    name: "4896 animated logo",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html", "css"],
    description: "",
    createdAt: "2021",
    link: "https://4896.top",
    images: ["./img/4896.png"],
  },
  {
    name: "Gooya personal website",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html", "VanillaJs"],
    description: "",
    createdAt: "2020",
    link: "https://pourghannad.github.io/gooyahiphop/",
    images: ["./img/gooya.png"],
  },
  {
    name: "Hubber dashboard",
    type: "website",
    design: "Reza Ghenaat",
    technology: [
      "react",
      "typescript",
      "material ui",
      "i18n",
      "redux-saga",
      "formik",
      "styled-components",
    ],
    memberOfTeam: true,
    description: "",
    createdAt: "2020",
    link: "",
    images: ["./img/hubber.png"],
  },
  {
    name: "Address Pwa",
    type: "pwa",
    design: "Address team",
    technology: [
      "react",
      "typescript",
      "webpack",
      "scss-modules",
      "workbox",
      "mapbox",
      "cypress",
    ],
    memberOfTeam: true,
    description: "",
    createdAt: "2020",
    link: "",
    images: ["./img/address-pwa-1.png"],
  },
  {
    name: "the-gate",
    type: "pwa",
    design: "",
    development: "Pourghannad",
    technology: [
      "react",
      "webpack",
      "i18n",
      "material ui",
      "redux-saga",
      "scss-modules",
    ],
    platform: [],
    description: "",
    createdAt: "2019",
    link: "",
    images: ["./img/the-gate.png"],
  },
  {
    name: "Address v2",
    type: "website",
    design: "address team",
    technology: [
      "react",
      "typescript",
      "redux thunk",
      "ant-design",
      "webpack",
      "scss-modules",
      "mapbox",
      "cypress",
    ],
    memberOfTeam: true,
    description: "",
    createdAt: "2019",
    link: "",
    images: [
      "./img/address-v2-1.png",
      "./img/address-v2-2.png",
      "./img/address-v2-3.png",
    ],
  },
  {
    name: "Address Backoffice v2 (Jahan 🌎)",
    type: "website",
    design: "",
    technology: ["react", "typescript", "leaflet"],
    memberOfTeam: true,
    description: "",
    createdAt: "2019",
    link: "",
    images: [],
  },
  {
    name: "Address Backoffice",
    type: "website",
    design: "",
    technology: ["react", "typescript", "ant-design"],
    memberOfTeam: true,
    description: "",
    createdAt: "2018",
    link: "",
    images: [],
  },
  {
    name: "Address v1",
    type: "website",
    design: "address team",
    technology: ["react", "typescript", "webpack", "ant-design"],
    memberOfTeam: true,
    description: "",
    createdAt: "2018",
    link: "",
    images: ["./img/address-v-1.png"],
  },
  {
    name: "3Mahi",
    type: "website",
    design: "Behnam Sobhkhiz",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2018",
    link: "",
    images: ["./img/3mahi.png"],
  },
  {
    name: "Gtick",
    type: "pwa",
    technology: ["react", "webpack", "leaflet"],
    design: "Behnam Sobhkhiz",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2018",
    link: "",
    images: ["./img/gtick.png"],
  },
  {
    name: "dopdots",
    type: "open-source",
    technology: ["VanillaJs", "canvas"],
    design: "Pourghannad",
    development: "Pourghannad",
    description: "",
    createdAt: "2018",
    link: "https://pourghannad.github.io/dopdots/",
    images: ["./img/dopdots.png"],
  },
  {
    name: "BaninaB website",
    type: "website",
    technology: ["react", "webpack"],
    design: "Pourghannad",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "https://pourghannad.github.io/BaninaB-website/#/fa",
    images: ["./img/baninab.png"],
  },
  {
    name: "DCMON 2",
    type: "pwa",
    technology: ["Angular4", "metronic-theme", "TypeScript", "webpack"],
    design: "baninab team",
    memberOfTeam: true,
    development: "baninab team",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [
      "./img/dcmon-1.png",
      "./img/dcmon-2.png",
      "./img/dcmon-3.png",
      "./img/dcmon-4.png",
      "./img/dcmon-5.png",
      "./img/dcmon-6.png",
    ],
  },
  {
    name: "Baniguard 2",
    type: "website",
    technology: ["scss", "Angular 4", "Node.js", "webpack", "TypeScript"],
    design: "",
    memberOfTeam: true,
    development: "baninab team",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "DCMON 1",
    type: "website",
    technology: ["jQuery", "gulp", "mustache.js"],
    design: "Pourghannad",
    memberOfTeam: true,
    development: "baninab team",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "Baniguard 1",
    type: "website",
    technology: ["scss", "AngularJS", "Node.js"],
    design: "",
    memberOfTeam: true,
    development: "baninab team",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "afzir customers panel",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: ["Wordpress"],
    description: "wordpress plugin for admin dashboard",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "entertainment database",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["Wordpress"],
    description: "",
    createdAt: "2017",
    link: "",
    images: ["./img/entertainment-database.jpg"],
  },
  {
    name: "unknown v2",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: [],
    description: "free wordpress template",
    createdAt: "2016",
    link: "",
    images: ["./img/unknown-v2.jpg", "./img/unknown-v2-1.png"],
  },
  {
    name: "food-center",
    type: "website",
    design: "Cretively Team",
    development: "Pourghannad",
    platform: ["Wordpress", "Woocommerce"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [
      "./img/food-center-1.png",
      "./img/food-center-2.png",
      "./img/food-center-3.png",
      "./img/food-center-4.png",
      "./img/food-center-5.png",
    ],
  },
  {
    name: "Cretively",
    type: "website",
    design: "Cretively Team",
    development: "Pourghannad",
    platform: ["Wordpress", "Woocommerce"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/cretively.jpg"],
  },
  {
    name: "HiMusic",
    type: "website",
    design: "Honargaran Farda",
    development: "Pourghannad",
    platform: ["Wordpress"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/himusic-1.png", "./img/himusic-2.png"],
  },
  {
    name: "tolidat melli",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    memberOfTeam: true,
    platform: ["html"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/tolidat-melli.png"],
  },
  {
    name: "sama",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/sama.jpg"],
  },
  {
    name: "oudlajan",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    platform: ["Woocommerce"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/oudlajan.jpg"],
  },
  {
    name: "mehrnegar",
    type: "website",
    design: "alireza arvin",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2016",
    link: "",
    images: ["./img/mehrnegar-1.jpg"],
  },
  {
    name: "design team 90theme v2",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html", "Jquery"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "iranian bank logo",
    type: "open-source",
    design: "",
    development: "Pourghannad",
    description: "iranian bank logo with svg and css animation",
    createdAt: "2016",
    link: "https://pourghannad.github.io/iranian-bank-logo/",
    images: ["./img/iranian-bank-logo-1.png"],
  },
  {
    name: "bazitak.ir",
    type: "website",
    design: "dornaweb",
    development: "Pourghannad",
    platform: ["WordPress", "Jquery"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/bazitak.jpg"],
  },
  {
    name: "90theme V2",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/90theme-v2-1.png", "./img/90theme-v2-2.png"],
  },
  {
    name: "enviar",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["mihalism"],
    description: "free mihalism template",
    createdAt: "2016",
    link: "",
    images: ["./img/enviar-1.png", "./img/enviar-2.png"],
  },
  {
    name: "design team 90theme",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    technology: ["html", "jquery"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/design-90theme-1-1.png", "./img/design-90theme-1-2.png"],
  },
  {
    name: "tanaz",
    type: "website",
    design: "Pourghannad",
    development: "alireza arvin",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2015",
    link: "",
    images: ["./img/tanaz.png"],
  },
  {
    name: "ircardshop",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["freer"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/ircardshop.png"],
  },
  {
    name: "perspolis fan",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/perspolis-fan.png"],
  },
  {
    name: "khat video",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/khatvideo.png"],
  },
  {
    name: "90theme 2.1",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/90theme2.1-1.png"],
  },
  {
    name: "nardeban bandegi",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/bandegi.png"],
  },
  {
    name: "90theme upload center",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["kleeja"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/up-90theme-1.png"],
  },
  {
    name: "8data",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: ["html", "whmcs"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/8data.png"],
  },
  {
    name: "bag iran",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/bag-iran-1.gif"],
  },
  {
    name: "luxpen",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/luxpen-1.gif"],
  },
  {
    name: "appleir",
    type: "website",
    design: "Apple iran",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/appleir.png"],
  },
  {
    name: "giyahan daroee",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/daroo-1.png"],
  },
  {
    name: "xscript",
    type: "website",
    design: "Pourghannad",
    development: "",
    platform: ["PSD"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/xscript.jpg"],
  },
  {
    name: "tarahanweb",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/tarahanweb-2.png", "./img/tarahanweb-1.png"],
  },
  {
    name: "20script upload center",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    platform: ["kleeja"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/20script-upload.png"],
  },
  {
    name: "learnspot",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/learnspot.gif"],
  },
  {
    name: "uploadbit",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["mihalism"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/uploadbit.png"],
  },
  {
    name: "diri",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/diri.gif"],
  },
  {
    name: "khatblog",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/khatblog.png"],
  },
  {
    name: "modemardan",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/modemardan.gif"],
  },
  {
    name: "iran news",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/iran-news.png"],
  },
  {
    name: "cloudha",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./cloudha.gif"],
  },
  {
    name: "unknown v1",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2015",
    link: "",
    images: ["./img/unkown-v1-1.png"],
  },
  {
    name: "bsi",
    type: "website",
    design: "Pourghannad",
    development: "",
    memberOfTeam: true,
    platform: [""],
    description: "website sketch for old platform",
    createdAt: "2015",
    link: "",
    images: ["./img/bsi-1.png", "./img/bsi-2.png", "./img/bsi-3.png"],
  },
  {
    name: "Chemizo",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/chemizo-1.png"],
  },
  {
    name: "avawebgostar",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/ava-1.gif"],
  },
  {
    name: "corederoma",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/corederoma.jpg", "./img/corederoma-1.png"],
  },
  {
    name: "iranvpn",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/iranvpn.jpg"],
  },
  {
    name: "MMMusic",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2015",
    link: "",
    images: ["./img/M2Music-1.jpg", "./img/M2Music-2.png"],
  },
  {
    name: "20script froum",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    platform: ["vbulletin"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/20script-forum.png"],
  },
  {
    name: "loxit",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["wordpress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/loxit-1.png"],
  },
  {
    name: "80200",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/80200.jpg"],
  },
  {
    name: "skimoo",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/skimoo.png", "./img/skimoo-1.png"],
  },
  {
    name: "tamin",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/tamin.png"],
  },
  {
    name: "Pourghannad.ir-v1",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/pourghannad-ir-v1.png"],
  },
  {
    name: "Kharid konam",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/kharidkonam.jpg"],
  },
  {
    name: "ArkaNet",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/arkanet.gif"],
  },
  {
    name: "MihanIT",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/mihanit.gif"],
  },
  {
    name: "WNovin",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/wnovin.gif"],
  },
  {
    name: "5host",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/5host.gif"],
  },
  {
    name: "data98",
    type: "website",
    design: "amir designer",
    development: "Pourghannad",
    platform: ["html", "whmcs"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/data98.png"],
  },
  {
    name: "niazmandiha",
    type: "website",
    design: "Pourghannad",
    development: "",
    platform: ["Wordpress"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/niazmandia.png"],
  },
  {
    name: "unity",
    type: "website",
    design: "alireza arvin",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2014",
    link: "",
    images: ["./img/unity.jpg"],
  },
  {
    name: "roid",
    type: "website",
    design: "alireza arvin",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2014",
    link: "",
    images: ["./img/roid.png"],
  },
  {
    name: "codespace",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/code-space.gif"],
  },
  {
    name: "isolate",
    type: "website",
    design: "alireza arvin",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2014",
    link: "",
    images: ["./img/isolate.png"],
  },
  {
    name: "filmS",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2014",
    link: "",
    images: ["./img/filmS.png"],
  },

  {
    name: "4color",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "free wordpress template",
    createdAt: "2014",
    link: "",
    images: ["./img/4color.png"],
  },
  {
    name: "Orpf landing",
    type: "website",
    design: "Erfan bagheri",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/orpf.png"],
  },
  {
    name: "Gembox",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/gembox.png"],
  },
  {
    name: "90theme 1.2",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/90theme-v1.2-2.png", "./img/90theme-v1.2-1.png"],
  },
  {
    name: "zhost",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/zhost.gif"],
  },
  {
    name: "90theme-version-1",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2013",
    link: "",
    images: [],
  },
];
