export const portfolio = [
  {
    name: "Hamrahtel Incredibles Landing",
    type: "website",
    design: "Hamrahtel Design team",
    development: "Pourghannad",
    technology: ["react", "typescript", "tailwind"],
    description: "",
    createdAt: "2025",
    link: "https://hamrahtel.com/incredibles",
    images: ["./img/hamrahtel-incredibles-landing.png"],
  },
  {
    name: "Hamrahtel App Landing",
    type: "website",
    design: "Hamrahtel Design team",
    development: "Pourghannad",
    technology: ["react", "typescript", "tailwind"],
    description: "",
    createdAt: "2025",
    link: "https://hamrahtel.com/app",
    images: ["./img/hamrahtel-app-landing.png"],
  },
  {
    name: "gsm.ir backoffice",
    type: "website",
    design: "Hamrahtel Design team",
    technology: [
      "react",
      "typescript",
      "vite",
      "react-query",
      "material-ui",
      "react-hook-form",
      "semantic-release",
      "workbox",
      "orval",
      "jotai",
      "i18n",
    ],
    description: "",
    createdAt: "2025",
    memberOfTeam: true,
    link: "https://gbo.gsm.ir/",
    images: [],
  },
  {
    name: "Hamrahtel warehouse",
    type: "website",
    design: "Hamrahtel Design team",
    technology: [
      "react",
      "typescript",
      "vite",
      "react-query",
      "jotai",
      "material-ui",
      "react-hook-form",
      "semantic-release",
      "workbox",
      "orval",
      "i18n",
    ],
    description: "",
    createdAt: "2025",
    memberOfTeam: true,
    link: "https://warehouse.hamrahtel.com/",
    images: ["./img/hamrahtel-warehouse.png"],
  },
  {
    name: "Hamrahtel backoffice",
    type: "website",
    design: "Hamrahtel Design team",
    technology: [
      "react",
      "typescript",
      "vite",
      "react-query",
      "material-ui",
      "react-hook-form",
      "jotai",
      "semantic-release",
      "workbox",
      "apollo",
      "graphql",
      "i18n",
    ],
    description: "",
    createdAt: "2025",
    memberOfTeam: true,
    link: "https://admin.hamrahtel.com/",
    images: ["./img/hamrahtel-admin.png"],
  },
  {
    name: "Hamrahtel pwa",
    type: "pwa",
    design: "Hamrahtel Design team",
    technology: [
      "react",
      "typescript",
      "react-query",
      "tailwind",
      "react-hook-form",
      "orval",
      "react-router-framework",
      "semantic-release",
      "workbox",
      "shadcn",
      "jotai",
      "graphql",
    ],
    description: "",
    createdAt: "2025",
    memberOfTeam: true,
    link: "https://app.hamrahtel.com/",
    images: [
      "./img/hamrahtel-app.png",
      "./img/hamrahtel-app-2.png",
      "./img/hamrahtel-app-3.png",
    ],
  },
  {
    name: "youCube twa",
    type: "pwa",
    design: "youCube Design team",
    technology: [
      "react",
      "typescript",
      "vite",
      "react-query",
      "jotai",
      "scss-modules",
      "react-hook-form",
    ],
    description: "",
    createdAt: "2024",
    memberOfTeam: true,
    link: "https://app.youcube.ai",
    images: ["./img/youcube.png", "./img/youcube2.png"],
  },
  {
    name: "youCube landing",
    type: "website",
    design: "Bahar Arsooni",
    technology: ["react", "scss", "react-helmet", "spline"],
    description: "",
    createdAt: "2024",
    memberOfTeam: true,
    link: "https://youcube.ai/",
    images: ["./img/ucube-landing.png"],
  },
  {
    name: "panj.monster",
    type: "logo",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html", "css"],
    description: "",
    createdAt: "2021",
    link: "https://pourghannad.github.io/panj.monster/",
    images: ["./img/panj-monster.png"],
  },
  {
    name: "karaz care",
    type: "website",
    design: "karaz design team",
    technology: ["nextjs", "material-ui", "jest", "styled-components"],
    description: "",
    createdAt: "2024",
    memberOfTeam: true,
    link: "",
    images: ["./img/karaz-care.png", "./img/karaz-care-2.png"],
  },
  {
    name: "karaz data panel",
    type: "website",
    design: "",
    technology: ["react", "material-ui", "material-react-table"],
    description: "",
    createdAt: "2024",
    link: "",
    images: [],
  },
  {
    name: "rapidpacecrm panel",
    type: "website",
    design: "roundtableapps design team",
    technology: ["react", "i18n", "micro-frontend", "redux-saga", "ant-design"],
    description: "",
    memberOfTeam: true,
    createdAt: "2023",
    link: "",
    images: ["./img/urm.png"],
  },
  {
    name: "rapidpacecrm",
    type: "website",
    design: "roundtableapps design team",
    technology: ["webflow"],
    description: "",
    memberOfTeam: true,
    createdAt: "2023",
    link: "https://rapidpacecrm.com",
    images: ["./img/rapidpace.png"],
  },
  {
    name: "Carriot backoffice",
    type: "website",
    design: "Carriot Design Team",
    technology: ["react", "typescript", "nextjs", "material ui", "gRPC"],
    description: "",
    memberOfTeam: true,
    createdAt: "2023",
    link: "https://panel.carriot.ir/login",
    images: ["./img/carriot.png"],
  },
  {
    name: "5Page",
    type: "open-source",
    design: "pourghannad",
    development: "pourghannad",
    technology: ["react", "scss-modules"],
    description: "",
    createdAt: "2022",
    link: "https://pourghannad.github.io/5page/",
    images: ["./img/5page.png"],
  },
  {
    name: "Sabaidea SSO V2",
    type: "website",
    design: "Sabaidea Design Team",
    technology: ["react", "typescript", "i18n"],
    description: "",
    memberOfTeam: true,
    createdAt: "2022",
    link: "https://www.filimo.com/signin",
    images: ["./img/sabaidea-sso.png"],
  },
  {
    name: "sc-weather",
    type: "open-source",
    design: "pourghannad",
    development: "pourghannad",
    technology: ["webpack", "scss", "VanillaJs"],
    description: "",
    createdAt: "2021",
    link: "https://azardnet.github.io/sc-weather/",
    images: ["./img/sc-weather.png"],
  },
  {
    name: "Aparat2",
    type: "website",
    design: "Sabaidea Design Team",
    technology: [
      "react",
      "typescript",
      "i18n",
      "redux-saga",
      "react-hook-form",
      "styled-components",
    ],
    description: "",
    memberOfTeam: true,
    createdAt: "2021",
    link: "https://aparat.com",
    images: ["./img/aparat.png"],
  },
  {
    name: "4896 animated logo",
    type: "logo",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html", "css"],
    description: "",
    createdAt: "2021",
    link: "https://4896.top",
    images: ["./img/4896.png"],
  },
  {
    name: "Gooya personal website",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html", "VanillaJs"],
    description: "",
    createdAt: "2020",
    link: "https://pourghannad.github.io/gooyahiphop/",
    images: ["./img/gooya.png"],
  },
  {
    name: "Hubber dashboard",
    type: "website",
    design: "Reza Ghenaat",
    technology: [
      "react",
      "typescript",
      "material ui",
      "i18n",
      "redux-saga",
      "formik",
      "styled-components",
    ],
    memberOfTeam: true,
    description: "",
    createdAt: "2020",
    link: "",
    images: ["./img/hubber.png"],
  },
  {
    name: "Address pwa",
    type: "pwa",
    design: "address design team",
    technology: [
      "react",
      "typescript",
      "webpack",
      "scss-modules",
      "workbox",
      "mapbox",
      "cypress",
    ],
    memberOfTeam: true,
    description: "",
    createdAt: "2020",
    link: "",
    images: ["./img/address-pwa-1.png"],
  },
  {
    name: "the-gate",
    type: "pwa",
    design: "",
    development: "Pourghannad",
    technology: [
      "react",
      "webpack",
      "i18n",
      "material ui",
      "redux-saga",
      "scss-modules",
    ],
    platform: [],
    description: "",
    createdAt: "2019",
    link: "",
    images: ["./img/the-gate.png"],
  },
  {
    name: "Address v2",
    type: "website",
    design: "address design team",
    technology: [
      "react",
      "typescript",
      "redux thunk",
      "ant-design",
      "webpack",
      "scss-modules",
      "mapbox",
      "cypress",
    ],
    memberOfTeam: true,
    description: "",
    createdAt: "2019",
    link: "",
    images: [
      "./img/address-v2-1.png",
      "./img/address-v2-2.png",
      "./img/address-v2-3.png",
    ],
  },
  {
    name: "Address Backoffice v2 (Jahan 🌎)",
    type: "website",
    design: "",
    technology: ["react", "typescript", "leaflet"],
    memberOfTeam: true,
    description: "",
    createdAt: "2019",
    link: "",
    images: [],
  },
  {
    name: "Address Backoffice",
    type: "website",
    design: "",
    technology: ["react", "typescript", "ant-design"],
    memberOfTeam: true,
    description: "",
    createdAt: "2018",
    link: "",
    images: [],
  },
  {
    name: "Address v1",
    type: "website",
    design: "address design team",
    technology: ["react", "typescript", "webpack", "ant-design"],
    memberOfTeam: true,
    description: "",
    createdAt: "2018",
    link: "",
    images: ["./img/address-v-1.png"],
  },
  {
    name: "3Mahi",
    type: "website",
    design: "Behnam Sobhkhiz",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2018",
    link: "",
    images: ["./img/3mahi.png"],
  },
  {
    name: "Gtick",
    type: "pwa",
    technology: ["react", "webpack", "leaflet"],
    design: "Behnam Sobhkhiz",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2018",
    link: "",
    images: [],
  },
  {
    name: "dopdots",
    type: "open-source",
    technology: ["VanillaJs", "canvas"],
    design: "Pourghannad",
    development: "Pourghannad",
    description: "",
    createdAt: "2018",
    link: "https://pourghannad.github.io/dopdots/",
    images: ["./img/dopdots.png"],
  },
  {
    name: "BaninaB website",
    type: "website",
    technology: ["react", "webpack"],
    design: "Pourghannad",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "https://pourghannad.github.io/BaninaB-website/#/fa",
    images: [],
  },
  {
    name: "DCMON 2",
    type: "web-application",
    technology: ["Angular4", "metronic-theme", "TypeScript", "webpack"],
    design: "baninab team",
    memberOfTeam: true,
    development: "baninab team",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [
      "./img/dcmon-1.png",
      "./img/dcmon-2.png",
      "./img/dcmon-3.png",
      "./img/dcmon-4.png",
      "./img/dcmon-5.png",
      "./img/dcmon-6.png",
    ],
  },
  {
    name: "Baniguard 2",
    type: "web-application",
    technology: ["scss", "Angular 4", "Node.js", "webpack", "TypeScript"],
    design: "",
    memberOfTeam: true,
    development: "baninab team",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "DCMON 1",
    type: "web-application",
    technology: ["jQuery", "gulp", "mustache.js"],
    design: "Pourghannad",
    memberOfTeam: true,
    development: "baninab team",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "Baniguard 1",
    type: "web-application",
    technology: ["scss", "AngularJS", "Node.js"],
    design: "",
    memberOfTeam: true,
    development: "baninab team",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "afzir customers panel",
    type: "wordpress-plugin",
    design: "",
    development: "Pourghannad",
    platform: ["Wordpress"],
    description: "",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "entertainment database",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2017",
    link: "",
    images: [],
  },
  {
    name: "unknown v2",
    type: "wordpress-template",
    design: "",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/unknown-v2.jpg"],
  },
  {
    name: "food-center",
    type: "website",
    design: "Cretively Design Team",
    development: "Pourghannad",
    platform: ["Woocommerce"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/food-center.jpg"],
  },
  {
    name: "Cretively",
    type: "website",
    design: "Cretively Design Team",
    development: "Pourghannad",
    platform: ["Woocommerce"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/cretively.jpg"],
  },
  {
    name: "tolidat melli",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    memberOfTeam: true,
    platform: ["html"],
    description: "",
    createdAt: "2016",
    link: "",
    images: ["./img/tolidat-melli.png"],
  },
  {
    name: "oudlajan",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    platform: ["Woocommerce"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/oudlajan.png"],
  },
  {
    name: "mehrnegar",
    type: "wordpress-template",
    design: "alireza arvin",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "design team 90theme v2",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html", "Jquery"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "iranian bank logo",
    type: "open-source",
    design: "",
    development: "Pourghannad",
    description: "iranian bank logo with svg and css animation",
    createdAt: "2016",
    link: "https://pourghannad.github.io/iranian-bank-logo/",
    images: [],
  },
  {
    name: "bazitak.ir",
    type: "website",
    design: "dornaweb",
    development: "Pourghannad",
    platform: ["WordPress", "Jquery"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "90theme v2",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "enviar",
    type: "mihalism-template",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["mihalism"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "design team 90theme",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    technology: ["html", "jquery"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "tanaz",
    type: "wordpress-template",
    design: "Pourghannad",
    development: "alireza arvin",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "ircardshop",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["freer"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "perspolis fan",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "khat video",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: [],
    description: "",
    createdAt: "2016",
    link: "",
    images: [],
  },
  {
    name: "nardeban bandegi",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "90theme upload center",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["kleeja"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "8data",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: ["html", "whmcs"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "data98",
    type: "website",
    design: "amir_designer",
    development: "Pourghannad",
    platform: ["wordpress", "whmcs"],
    description: "",
    createdAt: "2014",
    link: "",
    images: [],
  },
  {
    name: "niazmandiha",
    type: "website",
    design: "Pourghannad",
    development: "",
    platform: [],
    description: "",
    createdAt: "2014",
    link: "",
    images: [],
  },
  {
    name: "roid",
    type: "wordpress-template",
    design: "alireza arvin",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2014",
    link: "",
    images: [],
  },
  {
    name: "appleir",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "giyahan daroee",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "zhost",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "tamindisk",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "tarahanweb",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "learnspot",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "uploadbit",
    type: "banner",
    design: "Pourghannad",
    development: "",
    platform: ["banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "diri",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "khatblog",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "modemardan",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "iran news",
    type: "website",
    design: "",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "cloudha",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./cloudha.gif"],
  },
  {
    name: "unknown v1",
    type: "wordpress-template",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "avawebgostar",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "corederoma",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/corederoma.jpg"],
  },
  {
    name: "iranvpn",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "MMMusic",
    type: "wordpress-template",
    design: "-",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "20script froum",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    platform: ["vbulletin"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "loxit",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2015",
    link: "",
    images: [],
  },
  {
    name: "80200",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/80200.jpg"],
  },
  {
    name: "skimoo",
    type: "website",
    design: "ivahid",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2015",
    link: "",
    images: ["./img/skimoo.png"],
  },
  {
    name: "Pourghannad.ir-v1",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["html"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/pourghannad-ir-v1.png"],
  },
  {
    name: "ArkaNet",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/arkanet.gif"],
  },
  {
    name: "MihanIT",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/mihanit.gif"],
  },
  {
    name: "WNovin",
    type: "gif",
    design: "Pourghannad",
    development: "",
    platform: ["gif-banner"],
    description: "",
    createdAt: "2014",
    link: "",
    images: ["./img/wnovin.gif"],
  },
  {
    name: "90theme 1.2",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2014",
    link: "",
    images: [],
  },
  {
    name: "90theme-version-1",
    type: "website",
    design: "Pourghannad",
    development: "Pourghannad",
    platform: ["WordPress"],
    description: "",
    createdAt: "2013",
    link: "",
    images: [],
  },
];
